"""Resize the approved transparent master; preserve alpha and never redraw the logo."""
from pathlib import Path
import base64
from io import BytesIO
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
MASTER = ROOT / "assets/brand/quokka-transparent.png"
MASCOT = ROOT / "assets/brand/quokka-pointing.png"
COUPLE = ROOT / "assets/brand/quokka-couple.png"
source = Image.open(MASTER).convert("RGBA")
mascot = Image.open(MASCOT).convert("RGBA")
couple = Image.open(COUPLE).convert("RGBA")

def fit_image(image, size, margin=0.045):
    side = round(size * (1 - margin * 2))
    artwork = image.copy()
    artwork.thumbnail((side, side), Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", (size, size))
    canvas.alpha_composite(artwork, ((size - artwork.width) // 2, (size - artwork.height) // 2))
    return canvas

def icon(size, margin=0.045):
    return fit_image(source, size, margin)

def mascot_icon(size, margin=0.04):
    return fit_image(mascot, size, margin)

def couple_icon(size, margin=0.02):
    return fit_image(couple, size, margin)

def save(path, size, margin=0.045):
    icon(size, margin).save(ROOT / path, optimize=True)

for path, size in {
    "site/logo.png": 512, "site/favicon.png": 64, "site/icon.png": 512,
    "site/apple-touch-icon.png": 180, "site/store_icon_128.png": 128,
    "assets/brand/avatar.png": 1024,
}.items():
    save(path, size, 0.13 if "avatar" in path else 0.045)
mascot_icon(256).save(ROOT / "site/quokka-mascot.png", optimize=True)
couple_icon(256).save(ROOT / "site/quokka-couple.png", optimize=True)

folder = "src/extension/public/icons"
for size in (16, 32, 48, 128):
    for name in (f"icon-{size}.png", f"icon{size}.png"):
        save(f"{folder}/{name}", size)
for name in ("icon-store-128.png", "store_icon_128.png"):
    save(f"{folder}/{name}", 128)
save(f"{folder}/icon.png", 512)
for path in ("site/favicon.ico", f"{folder}/favicon.ico"):
    icon(64).save(ROOT / path, sizes=[(16, 16), (32, 32), (48, 48), (64, 64)])

logo_buffer = BytesIO()
icon(48).save(logo_buffer, format="PNG", optimize=True)
mascot_buffer = BytesIO()
mascot_icon(128).save(mascot_buffer, format="PNG", optimize=True)
couple_buffer = BytesIO()
couple_icon(128).save(couple_buffer, format="PNG", optimize=True)
(ROOT / "src/shared/brand.ts").write_text(
    '// Generated by scripts/build-brand-assets.py from the approved quokka brand assets.\n'
    f'export const BRAND_LOGO_DATA_URL = "data:image/png;base64,{base64.b64encode(logo_buffer.getvalue()).decode()}";\n'
    f'export const BRAND_QUOKKA_DATA_URL = "data:image/png;base64,{base64.b64encode(mascot_buffer.getvalue()).decode()}";\n'
    f'export const BRAND_QUOKKA_COUPLE_DATA_URL = "data:image/png;base64,{base64.b64encode(couple_buffer.getvalue()).decode()}";\n'
)
print("Updated website, avatar, favicon, extension icons, and embedded quokka art.")
