"""Resize the approved transparent master; preserve alpha and never redraw the logo."""
from pathlib import Path
import base64
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
MASTER = ROOT / "assets/brand/bear-transparent.png"
source = Image.open(MASTER).convert("RGBA")

def icon(size, margin=0.045):
    side = round(size * (1 - margin * 2))
    artwork = source.copy()
    artwork.thumbnail((side, side), Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", (size, size))
    canvas.alpha_composite(artwork, ((size - artwork.width) // 2, (size - artwork.height) // 2))
    return canvas

def save(path, size, margin=0.045):
    icon(size, margin).save(ROOT / path, optimize=True)

for path, size in {
    "site/logo.png": 512, "site/favicon.png": 64, "site/icon.png": 512,
    "site/apple-touch-icon.png": 180, "site/store_icon_128.png": 128,
    "assets/brand/avatar.png": 1024,
}.items():
    save(path, size, 0.13 if "avatar" in path else 0.045)

folder = "src/extension/public/icons"
for size in (16, 32, 48, 128):
    for name in (f"icon-{size}.png", f"icon{size}.png"):
        save(f"{folder}/{name}", size)
for name in ("icon-store-128.png", "store_icon_128.png"):
    save(f"{folder}/{name}", 128)
save(f"{folder}/icon.png", 512)
for path in ("site/favicon.ico", f"{folder}/favicon.ico"):
    icon(64).save(ROOT / path, sizes=[(16, 16), (32, 32), (48, 48), (64, 64)])

encoded = base64.b64encode((ROOT / folder / "icon-48.png").read_bytes()).decode()
(ROOT / "src/shared/brand.ts").write_text(
    '// Generated by scripts/build-brand-assets.py from assets/brand/bear-transparent.png.\n'
    f'export const BRAND_LOGO_DATA_URL = "data:image/png;base64,{encoded}";\n'
)
print("Updated website, avatar, favicon and extension icons from the transparent master.")
